[common]
synced_files = []

[[profiles]]
name = "starship"
synced_files = [".config/starship.toml"]

[[profiles.packages]]
name = "dotstate-bin"
manager = "pacman"
package_name = "dotstate-bin"
binary_name = "dotstate-bin"

[[profiles.packages]]
name = "lazygit"
manager = "pacman"
package_name = "lazygit"
binary_name = "lazygit"

[[profiles.packages]]
name = "tailscale"
manager = "pacman"
package_name = "tailscale"
binary_name = "tailscale"

[[profiles.packages]]
name = "btop"
manager = "pacman"
package_name = "btop"
binary_name = "btop"

[[profiles.packages]]
name = "fzf"
manager = "pacman"
package_name = "fzf"
binary_name = "fzf"

[[profiles.packages]]
name = "localsend"
manager = "pacman"
package_name = "localsend"
binary_name = "localsend"

[[profiles.packages]]
name = "eza"
manager = "pacman"
package_name = "eza"
binary_name = "eza"

[[profiles.packages]]
name = "yay"
manager = "pacman"
package_name = "yay"
binary_name = "yay"

[[profiles.packages]]
name = "github-cli"
manager = "pacman"
package_name = "github-cli"
binary_name = "github-cli"

[[profiles.packages]]
name = "python-pip"
manager = "pacman"
package_name = "python-pip"
binary_name = "python-pip"

[[profiles.packages]]
name = "terraform"
manager = "pacman"
package_name = "terraform"
binary_name = "terraform"

[[profiles.packages]]
name = "jq"
manager = "pacman"
package_name = "jq"
binary_name = "jq"

[[profiles.packages]]
name = "packer"
manager = "pacman"
package_name = "packer"
binary_name = "packer"

[[profiles.packages]]
name = "dotnet-sdk-8.0"
manager = "pacman"
package_name = "dotnet-sdk-8.0"
binary_name = "dotnet-sdk-8.0"

[[profiles.packages]]
name = "vim"
manager = "pacman"
package_name = "vim"
binary_name = "vim"

[[profiles.packages]]
name = "bitwarden"
manager = "pacman"
package_name = "bitwarden"
binary_name = "bitwarden"

[[profiles.packages]]
name = "keychain"
manager = "pacman"
package_name = "keychain"
binary_name = "keychain"

[[profiles.packages]]
name = "ripgrep"
manager = "pacman"
package_name = "ripgrep"
binary_name = "ripgrep"

[[profiles.packages]]
name = "azure-cli"
manager = "pacman"
package_name = "azure-cli"
binary_name = "azure-cli"

[[profiles.packages]]
name = "tmux"
manager = "pacman"
package_name = "tmux"
binary_name = "tmux"

[[profiles.packages]]
name = "man-db"
manager = "pacman"
package_name = "man-db"
binary_name = "man-db"

[[profiles.packages]]
name = "zsh"
manager = "pacman"
package_name = "zsh"
binary_name = "zsh"

[[profiles.packages]]
name = "neovim"
manager = "pacman"
package_name = "neovim"
binary_name = "neovim"

[[profiles.packages]]
name = "tree-sitter-cli"
manager = "pacman"
package_name = "tree-sitter-cli"
binary_name = "tree-sitter-cli"

[[profiles.packages]]
name = "zoxide"
manager = "pacman"
package_name = "zoxide"
binary_name = "zoxide"

[[profiles.packages]]
name = "tldr"
manager = "pacman"
package_name = "tldr"
binary_name = "tldr"

[[profiles.packages]]
name = "feishin-bin"
manager = "pacman"
package_name = "feishin-bin"
binary_name = "feishin-bin"

[[profiles.packages]]
name = "kubectl"
manager = "pacman"
package_name = "kubectl"
binary_name = "kubectl"

[[profiles.packages]]
name = "ghostty"
manager = "pacman"
package_name = "ghostty"
binary_name = "ghostty"

[[profiles.packages]]
name = "npm"
manager = "pacman"
package_name = "npm"
binary_name = "npm"

[[profiles.packages]]
name = "powershell-bin"
manager = "pacman"
package_name = "powershell-bin"
binary_name = "powershell-bin"

[[profiles.packages]]
name = "yazi"
manager = "pacman"
package_name = "yazi"
binary_name = "yazi"

[[profiles.packages]]
name = "git"
manager = "pacman"
package_name = "git"
binary_name = "git"

[[profiles]]
name = "tmux"
synced_files = [".tmux.conf"]
packages = []

[[profiles]]
name = "zsh"
synced_files = [".zshrc"]
packages = []

[[profiles]]
name = "bat"
synced_files = []
packages = []

[[profiles]]
name = "btop"
synced_files = []
packages = []

[[profiles]]
name = "lazygit"
synced_files = []
packages = []

[[profiles]]
name = "ghostty"
synced_files = []
packages = []

[[profiles]]
name = "nvim"
synced_files = []
packages = []
