add_newline = false

format = "$directory$git_branch$git_status$character"

[directory]
style = "bold #31748f"
format = "[$path]($style) "
truncation_length = 3

[git_branch]
symbol = "󰊢 "
style = "bold #ebbcba"
format = "on [$symbol$branch]($style) "

[git_status]
style = "#908caa"
format = "[($all_status$ahead_behind )]($style)"

[character]
success_symbol = "[󰄾](bold #f6c177) " 
error_symbol = "[󰄾](bold #eb6f92) "

[python]
symbol = " "
style = "#9ccfd8"
format = "[$symbol]($style)"

[rust]
symbol = " "
style = "#eb6f92"
format = "[$symbol]($style)"
